### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by niklas2233** [MORIMORI0317/GameMenuModOption#11]
Hey this mod seems to have a compatibility issue with mine together 

![XGMXsTR](https://user-images.githubusercontent.com/33903786/148492811-8c2ff75e-60b7-4347-a0ca-4172007e3775.png)

**Comment by MORIMORI0317** [comment]
What is the mod name to which the "Open to friends" button is added?

**Comment by niklas2233** [comment]
I would assume it's mine together since they add the friend feature. But I added the mod to oceanblock and  this happend

**Comment by MORIMORI0317** [comment]
It seems that the button layout was in conflict with MineTogether.
Added compatibility with MineTogether.
https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption/files/3600710

**Comment by niklas2233** [comment]
<3 thanks
