### ISSUE TITLE
Register DisplayTest extension point to prevent server list FML incompatibility notification

### ISSUE THREAD

**Issue by Mike5357** [MORIMORI0317/GameMenuModOption#12]
Add ModLoadingContext to prevent multiplayer servers from displaying as incompatible if the mod is installed on the client.
See https://mcforge.readthedocs.io/en/1.16.x/concepts/sides/#writing-one-sided-mods

![image](https://user-images.githubusercontent.com/12630858/148651561-2d34ce30-747c-41d6-8eed-b543a9368485.png)

**Comment by MORIMORI0317** [comment]
https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption/files/3599103
Fixed.

**Comment by Mike5357** [comment]
> https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption/files/3599103 Fixed.

Thanks! Could we get a 1.16.5 release as well please? 😄

**Comment by MORIMORI0317** [comment]
https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption/files/3599584
