### ISSUE TITLE
Error during the sided_setup phase with latest version of Forge.

### ISSUE THREAD

**Issue by Gamemassa** [MORIMORI0317/GameMenuModOption#14]
MC Version: 1.19
Forge Version: 41.0.85

Hi,
I tried to load Minecraft with this mod and the latest version of Forge and I got the following error message:
![image](https://user-images.githubusercontent.com/18667108/178123525-5f2cacdc-3f39-443c-b721-4be6fceabd24.png)
[crash-2022-07-09_17.37.20-fml.txt](https://github.com/MORIMORI0317/GameMenuModOption/files/9077973/crash-2022-07-09_17.37.20-fml.txt)

**Comment by MORIMORI0317** [comment]
https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption/files/3866681
Released a modified version!

**Comment by Gamemassa** [comment]
Can confirm, fixed version you just released is working. Thanks for the quick response!
