### ISSUE TITLE
Incorrect name?

### ISSUE THREAD

**Issue by Spittys** [MORIMORI0317/GameMenuModOption#15]
It seems like the new version made today is built for 1.19.1, when I use the mod it says I need to use JavaFML 42, and that I have 41. I have tested the version you made on the 10th, and it works fine. I think you just need to change the name to 1.19.1, thanks.

**Comment by MORIMORI0317** [comment]
I made a mistake in the version notation of the MOD name of Curse Forge and Modrinth.
"GameMenuModOption-1.19-1.18" -> "GameMenuModOption-1.19.1-1.18"
Please use "GameMenuModOption-1.19-1.17" when using with 1.19, and "GameMenuModOption-1.19.1-1.18" when using with 1.19.1.
There was a change when updating from 1.19 to 1.19.1, and the "Open to Lan" button now changes to "Player Reporting" when playing online, so just changing the version name will cause problems.
