### ISSUE TITLE
1.19.2 Modrinth specifity

### ISSUE THREAD

**Issue by ColonelGerdauf** [MORIMORI0317/GameMenuModOption#17]
There is an issue with the update specificity of the mod. It appears to be applied only to 1.19.1, when it is more useful to set the range from 1.19 to 1.19.2.

This will make updating the mods through launchers a bit of work, if not confusion.

**Comment by MORIMORI0317** [comment]
Not sure which version you are referring to, but I found a version that forgot to specify support for 1.19.2, so I fixed it.
https://modrinth.com/mod/gamemenumodoption/version/1.19-1.18

**Comment by ColonelGerdauf** [comment]
Sorry for forgetting the specific mod version. I had mistakenly assumed that it was implied where 1.18 was the latest version of that branch.

Anyways, thank you for the fix.
