### ISSUE TITLE
1.16.5- Pixelmon Seems to break it ...

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MORIMORI0317/GameMenuModOption#18]
I love this mod but Pixelmon breaks it can you add some more options - maybe anchor to top or bottom of screen?
![javaw_TjwjPR0FMI 1](https://github.com/MORIMORI0317/GameMenuModOption/assets/10351221/a6817c92-154e-4273-a694-35946c808bb3)

**Comment by P3rf3ctXZer0** [comment]
This is with remove GFARB
![javaw_rCYDkTjI9z 1](https://github.com/MORIMORI0317/GameMenuModOption/assets/10351221/7f7f1e4e-c5ef-42e5-b083-de29187ad815)

**Comment by Tanjiraaaaa** [comment]
I have this same issue.

**Comment by Tanjiraaaaa** [comment]
The version is 1.16.5 @Greg-21

**Comment by P3rf3ctXZer0** [comment]
Oh I no longer support pixelmon period let me close this for you.
