### ISSUE TITLE
Client Crash When Viewing Mod

### ISSUE THREAD

**Issue by Brittank88** [MORIMORI0317/GameMenuModOption#6]
Not sure exactly what caused GMMO to crash the game here, however, it seems like the mod in question may be missing some piece of information that GMMO expects (that's just my guess though).

[Crash Report](https://hatebin.com/sbzyvzpbqu)
`Minecraft 1.16.4`
`Forge 35.1.37`
`GameMenuModOption 1.4`

**Comment by MORIMORI0317** [comment]
GMMO is a mod that adds the "mods" button on the title screen to the game menu as well.
So the mod list is from Forge, this crash is a Forge spec or bug

When I actually checked it, it seems that it crashes when I click the specified MOD even though the specified logo file is not specified or does not exist

"ClassicCombat-1.16.4-universal.jar" etc. seems to crash for your mod pack

**Comment by MORIMORI0317** [comment]
![2021-01-23_00h50_26](https://user-images.githubusercontent.com/43478594/105512914-0b499480-5d15-11eb-9957-a520f5768531.png)

**Comment by Brittank88** [comment]
Ah, my apologies - I thought it was a custom implementation for some reason. Thanks for clearing that up! I'll close the issue now as it doesn't really relate to your mod. c:
