### ISSUE TITLE
crash on f3+esc

### ISSUE THREAD

**Issue by mastermc05** [MORIMORI0317/GameMenuModOption#7]
crash log https://gist.githubusercontent.com/natanfudge/71cc457998ee9aebea35468a639589f5/raw/0af06d384139ea8e6907cbb644241991ace39047/crash.txt
idk if there is necesary something else, i'll try to check and answer to all questions

**Comment by MORIMORI0317** [comment]
https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption/files/3255506
Fixed
