### ISSUE TITLE
Suggestion: Forge Update Notifications

### ISSUE THREAD

**Issue by DalekCraft2** [MORIMORI0317/GameMenuModOption#9]
Forge has a feature for displaying notifications on mods what are out of date. Could this mod also use that, at least in the main menu? I am unsure of whether it would work whilst in-game.

**Comment by MORIMORI0317** [comment]
![2021-04-12_23h34_48](https://user-images.githubusercontent.com/43478594/114411995-ad2b9f80-9be7-11eb-8ef6-ef684aff0f1e.png)
Display like this?

**Comment by DalekCraft2** [comment]
Ye.

**Comment by MORIMORI0317** [comment]
https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption/files/3273863
Added update notification function.

**Comment by Eric-01** [comment]
I have a strange feeling that the thing you've implemented is not exactly what they asked for. And because of that, your nice mod has now become a (Mixin) coremod :/

**Comment by DalekCraft2** [comment]
I do not know why you think that, nor what (Mixin) coremod means.

**Comment by Eric-01** [comment]
I'm sorry if I misunderstood you, but this sentence: "Could this mod also use that, at least in the main menu?" makes me feel like you want the green gem back on the "Mods..." button in the main menu, but:
1. It's a Forge thing implemented by its developers a looong time ago, then at some point they dropped it (probably during the huge 1.13 rewrite), but now it's back again for at least several months. No need for any third-party mods here.
2. Not every mod supports this feature (I think most don't) as it is an optional entry in the "mods.toml" file and requires some extra work from the mod developer.

**Comment by Eric-01** [comment]
I'm sorry if I misunderstood you, but this sentence: "Could this mod also use that, at least in the main menu?" makes me feel like you want the green gem back on the "Mods" button in the main menu, but:
1. It's a Forge thing implemented by its developers a looong time ago, then at some point they dropped it (probably during the huge 1.13 rewrite), but now it's back again for at least several months. No need for any third-party mods here.
2. Not every mod supports this feature (I think most don't) as it is an optional entry in the "mods.toml" file and requires some extra work from the mod developer.
